### ISSUE TITLE
CommentableEntity is null on "Create comment" form

### ISSUE THREAD

**Issue by javiersantos** [bjjr/d09#6]
Not sure why it's happening.

The list of `CommentableEntity` is displayed properly in the form to create a new comment (`/comment/create.do`). However, when the "Save" button is pressed, the CommentableEntity selected is not set in the Comment object.

![captura de pantalla de 2017-03-24 12-22-44](https://cloud.githubusercontent.com/assets/2229658/24292204/9bc41e6a-108c-11e7-93c6-e0d3001b7377.png)

**Comment by javiersantos** [comment]
`findOne(id)` doesn't work when using from `CommentableEntityService`. However, if you use the `findOne(id)` from the extended class it magically works.

**Comment by alejandrohall** [comment]
I solved the issue in this commit: https://github.com/bjjr/d09/commit/edc3dd22a144a3e8c759f660912a0f8d196ead33

You need to take into account that you dont need to display a list with all the possibles commentableEntitites, you will perform a comment over a commentableEntity, so you will pass the id of this commentableEntity to the controller and the controller will pass this id to the create method in the service and the service is which will retrieve the commentableEntity and set it to the Comment entity.
